src/ParallelTemperingPreprocessor.cpp
src/ParallelTemperingPreprocessor.h

The ParallelTemperingPreprocessor.h/cpp files need macros over the MPI calls to allow for metamake.sh to build

Patch - Fix building with metamake.sh

---

metamakeMPI.sh
src/ConfigSetup.cpp

This prevents cryptic errors when user tries to build both mpi and nonmpi versions of gomc.

Create new directory for MPI binaries & Fix the bug segfaulting in ConfigSetup when no multsim object is created

---

src/GPU/CalculateEnergyCUDAKernel.cu
src/GPU/CalculateEnergyCUDAKernel.cuh
src/GPU/CalculateEwaldCUDAKernel.cu
src/GPU/CalculateForceCUDAKernel.cu

2 Changes:  
1) Fix the index into Sigma_Sq array (Size 2);  threadID (old) -> box (new) In BoxForce
2) Commented out the 3 NDEBUG's in Ewald CUDA kernel for memcpy'ing sumRnew and sumInew.  There was a comment speculating on the possibility that these calls could be removed for release mode, but apparently they are necessary.  Since there is 3 of them, and I know MP works when all three are included (1 1 1), and doesn't work when none of them are included (0 0 0), then 6 different combinations are possible (if you make a truth table).  Perhaps someone with better knowledge of this code knows why they would or wouldn't be neccessary.  This would save me the trouble of evaluation each of these 6 extra possibilities.
[input.zip](https://github.com/GOMC-WSU/GOMC/files/5018991/input.zip)

Development branch fix

---

CMake/FileLists.cmake
metamake.sh
src/CPUSide.cpp
src/CPUSide.h
src/ConfigSetup.cpp
src/EnPartCntSampleOutput.cpp
src/EnPartCntSampleOutput.h
src/HistOutput.cpp
src/KernelDensityEstimator.cpp
src/KernelDensityEstimator.h

This commit  removes the compiler pragmas that prevent EnCntPartSample and Histogram from being usable in other ensembles.  To create a histogram in a non-GCMC ensemble, simply provide the same parameters to the config file you would in a GCMC run.
This commit also implements a Kernel Density Estimator which piggybacks off the EnCntPartSample class.  As of right now, only the Box Car kernel is implemented which creates N bins, where N is the number of samples, and the width of the bin is hard coded to 1.0 K.  Since the space KDE works in is continuous as opposed to discrete, the previously generated kde cannot be used reused in a new kde.  Instead of overwriting the values in the kde file, KDE's are given an index.
The format for the KDE file is as follows:
kde_index (0 to number of kdes …

Histogram all ensembles

---

src/GPU/CalculateEwaldCUDAKernel.cu

@LSchwiebert: It seems like the energy difference in second step was not caused by `BoxReciprocalSetup` and `BoxReciprocal`. I printed all the coordinates before getting to those functions on the second step and some coordinates were off slightly. At this point it was obvious that the first step was setting incorrect forces for atoms and molecules (which was causing different trial positions for second step). After printing all the forces (after `BoxForceReciprocal` function), it seemed like only the atoms with indexes of multiple of `64` were getting incorrect results. It was different each time as well. Which meant the first iteration of the following loop was giving incorrect result.
https://github.com/GOMC-WSU/GOMC/blob/cc553ea42397259fc43b01e6459887f1dbdb2095/src/GPU/CalculateEwaldCUD …

Fix to issue #226

---

src/FFSetup.cpp
src/FFSetup.h

If the PSF file has headers that end in _MIE, and **ParaTypeCharmm	 true**, we break and print : 
Error: CHARMM-Style parameter is set but EXOTIC-Style parameter header NONBONDED_MIE was found.
Either set EXOTIC-Style in config file or change the keyword
NONBONDED_MIE to NONBONDED in the parameter files.
or 
Error: CHARMM-Style parameter is set but EXOTIC-Style parameter header NBFIX_MIE was found.
Either set EXOTIC-Style in config file or change the keyword
NBFIX_MIE to NBFIX in the parameter files.
If the PSF file has headers "NONBONDED" or "NBFIX" and **ParaTypeExotic	 true** or  **ParaTypeMie	 true**, we break and print:
Error: EXOTIC-Style parameter is set but CHARMM-Style parameter header NONBONDED was found.
Either set CHARMM-Style in config file or change the keyword
NONBONDED to …

Error checking of PSF file for headers appropriate to forcefield type.

---

CMake/FileLists.cmake
src/BoxDimensions.cpp
src/BoxDimensionsNonOrth.cpp
src/ConfigSetup.cpp
src/ConfigSetup.h
src/DCDOutput.cpp
src/DCDOutput.h
src/DCDlib.cpp
src/DCDlib.h
src/ExtendedSystem.cpp
src/ExtendedSystem.h
src/PDBSetup.cpp
src/PDBSetup.h
src/Setup.h

This pull request enables GOMC to read in restart binary coordinates (**.coor**) and restart extended system file/s (**.xsc**). #253 
- The restart **xsc** file will override the cellbasis vector defined in coonfig file and cell length and angle stored in restart **pdb** file/s.
- The restart binary **coor**  will override the coordinates stored in restart **pdb** file/s.
- Use **extendedSystem**, followed by box number, and restart extended system file name (**.xsc**).
e.g. `extendedSystem 0 Eq_BOX_0_restart.xsc`
- Use **binCoordinates**, followed by box number, and restart binary file name (**.coor**).
e.g. `binCoordinates 0 Eq_BOX_0_restart.coor`
- Reading the restart extended system file (**.xsc**) and restart binary coordinates (**.coor**) are decoupled. Hence, user can
define either …

Read in restart binary coordinate and extended system file

---

src/ConfigSetup.cpp
src/ConfigSetup.h
src/FFSetup.cpp
src/FFSetup.h
src/Setup.h

GOMC can now read multiple parameter files. 
- Define multiple parameter files: e.g.
```
Parameters     ../../common/Par_PCN14_Noble_Gases_Charmm.inp
Parameters     ../../common/Par_TraPPE_Alkanes_CHARMM.inp
```

Reading Multi parameter files

---

src/DCDOutput.h

The issue was closing the dcd file in class destructor, while we have not opened any file to write DCD.

Fix to ERROR: Error closing DCD file` at the end of simulation

---

src/MolSetup.cpp

The logic for finding a molecule in the old KindMap was faulty.  I ran this on GEMC examples argon&krypton and butane&pfbutane.  This restores any functionality lost in the merge.  I will do more rigorous testing of output with our old parser and new parser.

Simplified the logic between two box psf parser.

---

src/PSFOutput.cpp
src/PSFOutput.h

This commit calculates the correct number of atoms, bonds, angles, and dihedrals for a split psf restart file and includes it in the header.

Fixed psf restart headers

---

src/DCDOutput.cpp

Since the xsc is a **restart** extended system file, I added `_restart` to the xsc file name.

Changinf xsc file name

---

lib/NumLib.h
src/moves/IntraSwap.h
src/moves/MoleculeTransfer.h

Change the logic of rejecting the swap or intra-swap move, when new configuration overlaps with other atoms. In new logic, when the Rosenbluth Weight of new configuration falls bellow threshold of 1.0e-38, move is rejected.

Reject swap/intra-swap move for bad configuraiton

---

src/CalculateEnergy.cpp
src/Ewald.cpp
src/Ewald.h
src/EwaldCached.cpp
src/EwaldCached.h
src/GPU/CalculateEwaldCUDAKernel.cu
src/GPU/CalculateEwaldCUDAKernel.cuh
src/GPU/ConstantDefinitionsCUDAKernel.cu
src/GPU/ConstantDefinitionsCUDAKernel.cuh
src/NoEwald.cpp
src/NoEwald.h
src/Simulation.cpp
src/moves/IntraMoleculeExchange1.h
src/moves/MultiParticle.h
src/moves/VolumeTransfer.h

Many of the changes are related to functions used only by MultiParticle, such as BoxForceReciprocal, but since the changes are relatively extensive, it would be better to be reviewed before being merged into the development branch.
I validated the code by creating a simpler, but less efficient and less elegant, patch to just rebuild the k-vectors for the current box dimensions when a MP move starts. In the tests I ran, the patched GPU and CPU codes are matching each other and are matching with this simpler patch.
It turns out that all the test codes were using sumInew and sumRnew in the MultiParticle::Prep() function to calculate box force for the old molecule positions. It should be using sumIref and sumRref, but the codes matched because they all were wrong. I created a simple function …

Recip patch

---

src/MoleculeLookup.cpp
src/MoleculeLookup.h
src/moves/MoleculeExchange1.h
src/moves/MoleculeExchange2.h
src/moves/MoleculeExchange3.h
src/moves/MoleculeTransfer.h

The ensembles which vary in particle number should use the number of eligible molecules in each box for calculating probabilities related to transferring molecules.  We now calculate this value at the beginning of a simulation and modify it (increment into box and decrement source box) when transferring a molecule.
Before 
After

Probabilities and Coefficients are calculated using only swappable molecules for molecule transfer and MEMC.

---

CMakeLists.txt
metamake.sh

This patch will do the following:
1. Disable `googletest` for intel compiler
2. Manually set  gcc compiler if intel compiler was not found.

Fix to #issue312

---

src/ConfigSetup.cpp
src/ConfigSetup.h
src/MolSetup.cpp

This pull request allows for the user to enter 100% swap moves without an error stating he needs to give a value for displacement moves.  Also, if the move percents don't add up to 100%, the percentages are normalized to 100%, and a warning is printed telling the user that this is happening.

Norm move perc

---

src/CalculateEnergy.cpp
src/FFExp6.h
src/FFParticle.cpp
src/FFShift.h
src/FFSwitch.h
src/FFSwitchMartini.h
src/cbmc/DCCrankShaftAng.cpp
src/cbmc/DCCrankShaftDih.cpp
src/cbmc/DCHedronCycle.cpp
src/cbmc/DCRotateOnAtom.cpp

Fix the error in calculating intra-nonbonded energies for polar system, where `rCutCoulomb` is different from `rCut`. Now we only Use the LJ cutoff (`rCut`) do calculate the intra-nonbonded energies. 
Increase the tolerance to 10 degree. If sum Angles +/- 10 was close to 360, we keep the angles rigid for cyclic molecules.

Fix to the issue #338 and issue #335

---

CMake/FileLists.cmake
src/CPUSide.cpp
src/CPUSide.h
src/ConfigSetup.cpp
src/ConfigSetup.h
src/ExtendedSystem.cpp
src/ExtendedSystem.h
src/ExtendedSystemOutput.cpp
src/ExtendedSystemOutput.h
src/PDBOutput.cpp
src/PDBSetup.cpp
src/System.cpp
src/System.h
src/UnitConst.h
src/Velocity.h
src/moves/CrankShaft.h
src/moves/IntraMoleculeExchange1.h
src/moves/IntraSwap.h
src/moves/MoleculeExchange1.h
src/moves/MoleculeTransfer.h
src/moves/MoveBase.h
src/moves/MultiParticle.h
src/moves/MultiParticleBrownianMotion.h
src/moves/Regrowth.h
src/moves/Rotation.h
src/moves/TargetedSwap.h
src/moves/Translate.h
src/moves/VolumeTransfer.h

During the MC simulation, for any accepted MC move (except volume move), the velocity of the atoms in the molecule that is affected by the move will be reinitialized using Maxwell-Boltzmann distribution. In accepted Multiparticle and MultiParticleBrownian move, which affect all molecules in the box, the velocity of all atoms in the box will be reinitialized using Maxwell-Boltzmann distribution. 
To read the binary velocity, similar to binary coordinates (*.coor), use the following keyword:
```
// example of  NVT or NPT ensemble
binVelocities  0   filename.vel
// example of  GEMC
binVelocities  0   filename_box_0.vel
binVelocities  1   filename_box_1.vel
```
The random velocity implementation is based on [NAMD implementation](https://www.ks.uiuc.edu/Research/namd/mailing_list/namd-l.2011-20 …

Reading, updating, and outputting binary Velocity file

---

src/PDBOutput.cpp

Fix for corner case where the original kind index (Ar - 0; Kr - 1) changes due to no Ar being present in Box 0, thus the kind indices would be different from the original kind index (Ar - 1; Kr - 0).  The code already had this feature just had to change the indexing to use the placement index in a trajectory, not the data index in the molecule data.

quick fix to use right index for kinds in InitPartVec

---

src/ConfigSetup.cpp
src/ConfigSetup.h

If the user provides "ExpertMode true" in the config file, then Volume, Transfer, and Displacement moves no longer need to exist in the Config file at all, no matter what ensemble.  These values will be set to zero.

Added Config parameter "ExpertMode bool" (default false)

---

src/BlockOutput.cpp
src/ConsoleOutput.cpp
src/ConsoleOutput.h
src/OutConst.cpp
src/OutConst.h
src/OutputVars.cpp
src/OutputVars.h

Currently Enthalpy needs to be hand calculated from TOT_EN, pressure and volume of the system. This small cosmetic change prints enthalpy as calculated by formula H = U + PV (in units of kJ/mol), and compressibility as calculated by formula Z = PV/nRT.

Implemented box specific enthalpy and compressibility calculations and printing to block averages, as well as compressibility to log files.

---

src/GPU/CUDAMemoryManager.cu

The CUDA Memory Manager, which tracks allocations and deallocations of CUDA memory, doesn't work properly for the edge  case of allocating zero bytes of memory. First, it should generate a warning, as there isn't a good reason to allocate zero bytes.
And, if done multiple times, generates a spurious warning message when freeing the variables, as CudaMalloc maps all allocations of zero bytes map to nullptr, so the multiple allocations of zero bytes end up stepping on each other in the lookup table, as they don't have unique addresses.
The patch changes the code so that it (a) generates a warning when allocating zero bytes and (b) doesn't generate a warning when freeing an allocation with an address of nullptr. Note that the code does check at some point to make sure that all allocations …

Improve CUDA Memory Manager behavior for some edge cases -- Fixes issue #401

---

lib/NumLib.h
src/FFExp6.h
src/FFParticle.cpp
src/FFParticle.h
src/FFSetup.cpp
src/FFSetup.h
src/FFShift.h
src/FFSwitch.h
src/FFSwitchMartini.h

The patch removes the #define MIE_INT_ONLY and corrects an error in the ffsetup::Particle that always used uint for the exponents.

Fix #407 Mie potential with non-integer repulsion exponents

---

src/ConsoleOutput.cpp
src/ConsoleOutput.h

This is a small patch that prevents the console headers from printing twice when the output is printed every step. Added a boolean variable so that the headers are printed only the first time, instead of using step==0 as a special value.

Fix #414 GOMC prints console headers twice when printing every step

---

src/MolSetup.cpp

Added "\n" to some of the error message so that the command prompt prints on a separate line and not at the end of the error message. Did not change some statements like this:
fprintf(stderr, "ERROR: Could not find all atoms in PSF file ");
because I'm not sure whether it prints some more data when it returns from the function call. (The space after the word "file" is suggestive of a filename being output upon return.

Fix #379 Cleaner error messages in MolSetup.cpp

---

src/Checkpoint.h
src/CheckpointSetup.cpp
src/Molecules.cpp
src/Molecules.h
src/PDBOutput.cpp
src/PDBOutput.h
src/PDBSetup.cpp
src/PDBSetup.h

The occupancy column of PDB restart files is currently being zero'ed out no matter what.  This PR adjusts the behavior to print whatever the occupancy of that atom was at the start of the simulation.  Note, the PDB trajectories still replace the occupancy column with the box id that atom occupies.  This PR only changes restart PDB occ column.  
This will allow pyMCMD users to group atoms to form col vars using the occ column as a reference.  Also, the occ column could be used for continuing Free Energy calculations in namd, by using the occ column as lambda
Example run.  Changed the occ of atom 1 from 0.0 to 4.0;  The occ stays 4.0 after the first run and after continuing from checkpoint.
[val.zip](https://github.com/GOMC-WSU/GOMC/files/7866715/val.zip)
.

Restart pdb uses the atoms' input occupancy instead of overwriting occ with 0.

---

src/PDBOutput.cpp
src/PDBOutput.h

I forgot to push my last commit before merging the occupancy PR.  I converted the restart and pdb trajectory InsertAtomInLine methods to one method with a templated parameter
Validation attached.
[Base.zip](https://github.com/GOMC-WSU/GOMC/files/7886181/Base.zip)
.

Made OCC PR a template

---

src/CalculateEnergy.cpp
src/ConfigSetup.cpp
src/ConfigSetup.h
src/FFExp6.h
src/FFParticle.cpp
src/FFParticle.h
src/FFShift.h
src/FFSwitch.h
src/FFSwitchMartini.h
src/Forcefield.cpp
src/Forcefield.h
src/Molecules.cpp

Add support for Impulse Pressure Correction (IPC) for truncated potential (e.g. Mie and Exp-6) that does not utilize any long range correction (LRC). 
IPC only add correction term to pressure calculation and unlike LRC, it has no effect on energy.
Simply include `IPC  true` keyword into your config file.
**Note:** You can only use this feature if  `LRC  false`

Add support for Impulse Pressure Correction (IPC)

---

src/ConfigSetup.cpp
src/ConfigSetup.h

GOMC terminates if the config file includes the line
Checkpoint False
with the error message that the checkpoint file "False" cannot be opened.
The patch tests the input when Checkpoint has only one parameter. When it is a boolean string, like False or On, then the parameter is not interpreted as a filename. If the parameter is not a boolean string, then it is interpreted as the checkpoint filename.
The patch tests for the case and terminates if "Checkpoint True" is entered without providing the filename.

Fix #421 GOMC terminates on input Checkpoint False

---

src/CalculateEnergy.cpp
src/ConfigSetup.cpp
src/moves/MultiParticle.h
src/moves/MultiParticleBrownianMotion.h

1. Fix some warning output for IPC calculation.
2. Copy the atom force, mol force, and mol torque from reference variable to new variable when we simulating system with more than 1 box (GCMC and GEMC). 
3. Fix torque calculation to only override the value of the molecule index we are operating on.
4. Fix some warning output for IPC calculation.

Fix some minor issue in Multiparticle and brownian like Multiparticle

---

src/moves/IntraMoleculeExchange1.h
src/moves/IntraMoleculeExchange2.h
src/moves/IntraMoleculeExchange3.h

This patch fixes the bug that resulted in the acceptance term for the IntraMEMC moves using the wrong change in reciprocal energy.
This could result in accepting some moves that should not have been accepted or rejecting some moves that should have been accepted. The energy was updated correctly.
Fixes issue #425  for a bug that was introduced in the fix for issue #234.

Fix #425 use the correct recip energy for IntraMEMC move acceptance

---

lib/Endian.h

Tests don't build without this include statement.

Add #include <stdint.h> to Endian.h

---

src/moves/NeMTMC.h

This is a patch so that the NeMT move will call the Brownian Motion MP move in RelaxingTransform when it should.

Fix Issue #434: If defined, use Brownian Motion MP moves with NeMT

---

src/ConfigSetup.cpp

The code is now generating an error message if Chemical Potential and Fugacity is defined for the same resName, or if either is used more than once. The code correctly checks for this, but please review the error message for clarity before improving the pull request.

Fix #445: Error message if specifying Chemical Potential and Fugacity

---

src/CheckpointOutput.cpp
src/ConfigSetup.cpp
src/ConfigSetup.h
src/EnergyTypes.h
src/ExtendedSystem.cpp
src/MoveSettings.cpp
src/OutputAbstracts.h
src/PRNGSetup.cpp
src/Writer.h

To allow the user the flexibility of choosing the ability to roughly continue or exactly continue a simulation, RestartFreq and CheckpointFreq are now separate options. However, CheckpointFreq must equal RestartFreq and one cannot use CheckpointFreq without also setting RestartFreq.
The following cases were tested:
Initial Run - Restart False Checkpoint False
[intitialLog.txt](https://github.com/GOMC-WSU/GOMC/files/9144640/intitialLog.txt)
[in.conf.txt](https://github.com/GOMC-WSU/GOMC/files/9144641/in.conf.txt)
Continue Initial Run with Restart only - Restart True Checkpoint False; XSC/COOR files provided; Basis vectors removed from conf file
[restBinLog.txt](https://github.com/GOMC-WSU/GOMC/files/9144646/restBinLog.txt)
[rest.conf.txt](https://github.com/GOMC-WSU/GOMC/files/9144647/rest. …

Adds the CheckpointFreq option

---

src/OutConst.cpp

The block files can't be loaded because two labels are not space separated. Shortening the name of the label will resolve the problem.

Shorten ENERGY_LRC name to fix issue #458

---

src/ConsoleOutput.cpp
src/ConsoleOutput.h

Instead of tracking a value in the OutputVariables, there was a manually calculated value of entropy in the ENER_ line of console out.  This was removed, since the tracked variable for entropy is already printed in the STAT_ line.  This line also matches the Blk files.
Also, precision of console outputs is now 8 decimal points to match Block outputs.
BPTI/TIP3 example
[log.txt](https://github.com/GOMC-WSU/GOMC/files/9183397/log.txt)
[Blk_0.txt](https://github.com/GOMC-WSU/GOMC/files/9183398/Blk_0.txt)
[Blk_1.txt](https://github.com/GOMC-WSU/GOMC/files/9183399/Blk_1.txt)

remove bad console entry and increase precision of console outputs to match block output

---

src/ConfigSetup.cpp

Fixes the example in the error message when Checkpoint Frequency != Restart Frequency.

Fix issue #461 Checkpoint Output suggestion is incorrect

---

src/FFParticle.cpp
src/FFSetup.cpp

Low values for the exponent (<= 6.0) could result in division by zero. This patch resolves issue #463 by doing better error handling on the input Mie potentials. Error messages are generated if the exponents are too small.
If epsilon = 0 then the exponent is adjusted to avoid division by zero and the simulation continues, as these exponents aren't used in this case.

Fix #463: Simulations with Mie potential could produce NaNs and terminate

---

src/EnergyTypes.h

The ComparePotentials function had incorrect logic for checking the energies. And it was not returning a value when the potentials matched. I made three changes to the code. This should be checked carefully to ensure the logic is now correct. The changes are.
1. Only bond, angle, and dihedral are checked within the if case where the intraBond energies do not match.
2. The recip, real, self, and correction energies are checked only if the totalElect energies do not match.
3. The return value is set to false when the totalElect or intraBond energies don't match  and not set again when any components don't match.
4. The code returns the return value, true or false, in all cases.
Note that I don't think this caused any incorrect output, because it doesn't look like this function is actually …

Fix logic in ComparePotentials function

---

test/README.md
test/Setup_Examples.sh

Modified testing setup script to clone quick_testing branch of GOMC_Examples and remove all but NPT/DME example to get python data parsing and analysis working.

shorten and eliminate most examples for testing integration scripts

---

src/DCDlib.cpp
src/DCDlib.h

The current version of NAMD_write exits with a generic error message if the write() function returns an error.
This patch uses strerror() to print the text description of the error.
In addition, it retries up to 5 times, which is beneficial if there are transient errors.
Note that I was unable to reproduce this problem. The transient I/O errors disappeared once I wrote this patch. But the code is unchanged when the write() function succeeds. And the old code terminated immediately upon an error. So, I think there is very minimal if any risk in merging this patch even if it is incorrect.

Make NAMD_write more robust and informative on write errors

---

lib/Endian.h
src/CalculateEnergy.cpp
src/CalculateEnergy.h
src/Clock.h
src/ConsoleOutput.cpp
src/EnergyTypes.h
src/Simulation.cpp
src/moves/CrankShaft.h
src/moves/IntraSwap.h
src/moves/IntraTargetedSwap.h
src/moves/MoleculeTransfer.h
src/moves/Regrowth.h
src/moves/TargetedSwap.h

Treating the energy members as public variables, and accessing them from multiple locations in the code is sloppy and difficult to maintain.  The EnergyType variables should be made private and only modified/set by the CalcEn function of each move.  This requires specifying one method signature for all the moves, instead of the current two formed approach.
Non-cbmc moves take a molecule index as the argument
CBMC moves pass a CBMC molecule object.
The molecule index can be used to retrieve a CBMC object, so it seems the molecule index should be passed to all methods as the argument, and CBMC moves can create/retrieve the CBMC molecule object internally.
Until this is finalized, this PR reverts the hacked together intraBonded terms.

Revert the sloppy intraBonded PR

---

.github/workflows/ccpp.yml
CMakeLists.txt
src/CalculateEnergy.cpp
src/EnsemblePreprocessor.h
src/Ewald.cpp
src/EwaldCached.cpp
src/XYZArray.h

1. There is no need for checking `gcc` version. `firstprivate()` works on pre/post openmp 4.5; https://gcc.gnu.org/gcc-9/porting_to.html
2. I also added clang-tidy requirement to `cmake`. Meaning the code has to match clang-tidy's standards to even compile. `set(CMAKE_CXX_CLANG_TIDY clang-tidy -checks=-*,mpi-*,openmp-*)` does this. The first part (`-*`) disables all checks, and then adds any checks that starts with `mpi` and `openmp`. Code currently passes for these two. Once we do more clean ups we can add more check here.

Cleanup openmp commands.

---

src/EnergyTypes.h

When printing energies using the << operator, which is available only in debug mode, some ostream settings might not be reset to their original values because some code was placed inside an if block that should always executed.

Move some needed code outside an if block

---

src/MoleculeLookup.h

See description on Pull Request. The patch works as follows:
std::find( ) looks at the values in the specified range of the array and returns the last, which is not in the array. (For instance, if your array length is 100, you pass 0 and 100 and it returns 100 if not found, but a[100] is not in the array.) If it finds the value, it returns the appropriate index.
The code checks that the index is in the correct range (less than the upper bound). If it matches the upper bound, then you return false.

Fix #486 Resolve OOB read in IsMoleculeInBox when not found

---

src/CalculateEnergy.cpp
src/ConsoleOutput.cpp
src/Coordinates.cpp
src/GPU/CalculateForceCUDAKernel.cu
src/PRNG.h
src/XYZArray.h
src/moves/IntraMoleculeExchange1.h
src/moves/IntraMoleculeExchange2.h
src/moves/IntraMoleculeExchange3.h
src/moves/IntraSwap.h
src/moves/IntraTargetedSwap.h
src/moves/MoleculeExchange1.h
src/moves/MoleculeExchange2.h
src/moves/MoleculeExchange3.h

Fix issue #498. It turns out that gcc is not compiling the code correctly when we are making a call to a Mersenne Twister rand() function and using the output as a function parameter. In other words, the call to rand() appears in the function call. This causes the icc and gcc code to generate different results.
This happens with gcc 7.3. Might be fixed in a newer version of gcc, but need to produce a correct sequence of random numbers for any compiler, hence this patch.

Change Mersenne Twister function call usage so that icc and gcc compilations produce matching results

---

src/ConfigSetup.cpp

Resolves Issue #500 by making sure that a user who specifies a restart file in the config file can't run without also setting Restart to true.
This solution is more flexible in handling user errors in the config file than just setting Restart to true in these cases.

Check all restart files to make sure Restart is true

---

src/ConfigSetup.cpp

This PR changes the "warning" to an "error" for users that specify both the SWITCH function and long-range corrections at the same time.   Additionally, all "Error" text has been changed to "ERROR" and some of the error messages have been updated to correct grammar.

update SWITCH and LRC ERROR condition

---

src/ConfigSetup.cpp
src/FFSetup.cpp

Updating console output replacing the word "EXOTIC" with "Mie" when referring to the parameter file loaded.  Also includes a fix for the IPC and LRC checking in ConfigSetup.cpp  Previously, if LRC and IPC == false the simulation would flag that as an error, but this isn't a problem.  Meanwhile, it didn't check for the condition we want to avoid (both IPC and LRC true).

update console output

---

src/GPU/TransformParticlesCUDAKernel.cu
src/GPU/TransformParticlesCUDAKernel.cuh
src/MoveConst.h
src/MoveSettings.cpp
src/moves/MultiParticle.h
src/moves/MultiParticleBrownianMotion.h
src/moves/NeMTMC.h
src/moves/Regrowth.h

This patch makes bad MP moves produce a warning rather than an error. It also tries to reduce the frequency of bad MP moves with Brownian Motion by starting with a smaller initial move amount.

Change bad MP moves from error to warning

---

src/FFExp6.h
src/GPU/ConstantDefinitionsCUDAKernel.cu
src/GPU/ConstantDefinitionsCUDAKernel.cuh

This PR resolved issue #512. The code needed to have a function to deallocate the variables.
I also changed the names for these two GPU functions (Init and Destroy) for the Exp6 variables to be consistent with similar function names. And I moved some function definitions in the header file to organize things better.

Free the GPU variables allocated for the Exp6 Forcefield

---

src/BlockOutput.h

The code for computing the number of steps from the checkpoint to the first output of block averages was wrong when we were restarting.
The correct values were being computed by the system, but we output the wrong block averages because the code calculated the number of steps incorrectly, so had the wrong denominator.
The patch has been tested against the example provided in issue #514 and is now producing the expected output.

Fix issue #514: Output correct block averages first time after restart

---

src/ConfigSetup.cpp
src/ConfigSetup.h
src/StaticVals.cpp
src/StaticVals.h
src/moves/MultiParticle.h
src/moves/MultiParticleBrownianMotion.h

This patch resolves issue #520 by adding two boolean flags that can be used in the config file. The flags are:
MultipleParticleLiquid
MultipleParticleGas
The default settings are true for the liquid box and false for the gas box. The boxes are labeled at runtime, before running each move, based on the density of each box.
This applies only to GEMC simulations. The idea is that a MP move typically makes sense to be run in the liquid box because of the higher box density, however, any combination of flags is valid, except for setting both to false, since that would prevent the MP move from working.
This patch works for both force-based MP and Brownian-motion MP moves. It does not change the behavior of the NeMT move, which picks the box via a different process.

Allows GEMC simulations to control which boxes run MP moves

---

src/FFSetup.cpp
src/FFSetup.h
src/Reader.h

Resolves issue #529 by issuing a warning when dihedrals with matching periodicities are found. The duplicates are removed and a warning is generated. The warning looks like this:
Warning: Skipping duplicate periodicity of 3 for dihedral HCCTCTHC!

Detect and remove duplicate dihedrals with the same periodicity

---

src/ConfigSetup.cpp

This patches issue #531, which explains that a configuration file that uses the Intra-MEMC1 move will print the wrong move is being used.

Correct log entry for Intra-MEMC1 move

---

lib/BasicTypes.h

This pull request creates a more efficient implementation of many of the overloaded operators for the XYZ class. It should run faster and is more readable. It is a cleaner C++ implementation of the XYZ class.
It also changes the XYZ struct to an XYZ class, although making the data members private is complicated by the fact that many other classes access these variables directly. So, they are currently kept as public members.
Also, removed some unused types and UNUSED, which isn't used in the code.

Optimize operator overloading for XYZ objects

---

src/BlockOutput.h
src/ConfigSetup.cpp
src/Ewald.cpp
src/FFParticle.cpp
src/Forcefield.h
src/GPU/CUDAMemoryManager.cuh
src/GPU/CalculateEnergyCUDAKernel.cuh
src/GPU/CalculateEwaldCUDAKernel.cu
src/GPU/CalculateEwaldCUDAKernel.cuh
src/GPU/CalculateForceCUDAKernel.cu
src/GPU/CalculateForceCUDAKernel.cuh
src/GPU/ConstantDefinitionsCUDAKernel.cu
src/GPU/ConstantDefinitionsCUDAKernel.cuh
src/GPU/VariablesCUDA.cuh

The CPU and GPU can have different values for alpha^2. The reason is that the CPU apparently calculates a more accurate value of alpha^2 by using an intermediate value of alpha that is accurate to more than 64 bits, which it then squares.
To resolve this problem, the code has been changed to add new variables, gpu_alphaSq, gpu_rCutSq, and gpu_rCutCoulombSq, that are passed to the GPU, so the GPU uses the same values as the CPU for these variables. This also reduces the amount of computation, as we remove a multiplication each time we need the value of alpha^2.
The code is also updated to use the new alpha^2 value instead of recalculating it.
Unfortunately, the code also includes some reformatting of some files using clang-format, so the patch is larger than needed to resolve this issue.

Forcefield params do not match between CPU and GPU

---

src/cbmc/DCFreeCycle.cpp
src/cbmc/DCFreeCycleSeed.cpp
src/cbmc/DCFreeHedron.cpp
src/cbmc/DCFreeHedronSeed.cpp
src/cbmc/DCRotateCOM.cpp

The previous patch for issue #498 didn't address the problem for functions that were in the CBMC branch, so the same problem of inconsistent results was recurring for simulations that ran on gcc versus icc.
This patch updates those files. Also did a search and there don't seem to be any other function calls that might have this same problem, so hopefully this patch resolves the issue completely.

Fix calls to Mersenne Twister for CBMC functions

---

src/Main.cpp

The GOMC output lists the current OpenMP version, such as 4.5, by mapping the OpenMP version date code to the OpenMP version. For instance, the date code 201511 corresponds to OpenMP version 4.5. This patch adds newer OpenMP date codes to the lookup table. Otherwise, the code prints out the date code instead of the corresponding version.

Recognize newer OpenMP version date codes

---

src/Simulation.cpp

If the initial configuration is physically impossible, such as having two atoms in the same initial position, then GOMC will produce an initial energy that is infinite or NaN. For this case, the simulation won't self-correct to a feasible system. So, we should terminate with an error message so that the user can fix the initial configuration.
This patch introduces code to handle this situation.

Terminate GOMC (with an error message) if the initial configuration has infinite energy
