GOMC-WSU/GOMC

src/Main.cc
We now print out CPU and memory info before running the simulation.
=> Added hardware info

src/ConfigSetup.cpp, src/ConfigSetup.h
I want to merge this branch. Please verify it.
=> Case sensitive

.gitignore, .vscode/c_cpp_properties.json, .vscode/settings.json, CMake/FileLists.cmake, src/CPUSide.cpp, src/CPUSide.h, src/CheckpointOutput.cpp, src/CheckpointOutput.h, src/CheckpointSetup.cpp, src/CheckpointSetup.h, src/Clock.h, src/ConfigSetup.cpp, src/ConfigSetup.h, src/MersenneTwister.h, src/MoleculeLookup.cpp, src/MoleculeLookup.h, src/MoveSettings.h, src/PDBOutput.cpp, src/PRNG.h, src/Setup.h, src/Simulation.cpp, src/Simulation.h, src/System.cpp, src/System.h
This feature is ready. Should I merge it to development or wait until next release?
=> Checkpoint

CMake/FileLists.cmake, lib/BasicTypes.h, src/BoxDimensions.h, src/ConfigSetup.cpp, src/ConfigSetup.h, src/ConsoleOutput.cpp, src/MoveConst.h, src/MoveSettings.cpp, src/MoveSettings.h, src/PRNG.h, src/StaticVals.cpp, src/System.cpp, src/moves/MultiParticle.h, src/moves/MultiParticleBrownianMotion.h
You can switch the branch from development to any other branch. issue #159
=> Multi-particle brownian motion

src/GPU/CalculateEnergyCUDAKernel.cu, src/GPU/CalculateEnergyCUDAKernel.cuh
Fixes the last two sigmaSq indexing, and passes pointers to all the functions, allowing them to index further down the method trace.
=> Sigma sq index correction

src/CalculateEnergy.cpp, src/EnsemblePreprocessor.h, src/GPU/CalculateForceCUDAKernel.cu, src/GPU/TransformParticlesCUDAKernel.cu, src/GPU/TransformParticlesCUDAKernel.cuh, src/moves/MultiParticle.h
Fixed a bug where Transform was moving particles in both boxes in GCMC ensemble.
=> Fixed GPU bug for GCMC

src/ConfigSetup.cpp
Removed requirement user input histogram setup parameters in config file.
=> Histogram all ensembles

src/CalculateEnergy.cpp, src/CalculateEnergy.h, src/GPU/TransformParticlesCUDAKernel.cu, src/GPU/TransformParticlesCUDAKernel.cuh, src/MoveSettings.cpp, src/MoveSettings.h, src/moves/MultiParticle.h
This PR fixes issues #220 and #221
=> Two bugs related to GPU Multiparticle

src/Ewald.cpp, src/EwaldCached.cpp, src/moves/MultiParticle.h
Windows OpenMP requires signed integers for body of the loop.
=> Changed uint to int so Visual Studio 2019 compiles as well

src/Ewald.cpp, src/Simulation.cpp, src/Simulation.h
Reverting back changes in `UpdateRecip()`.
=> bug fix #234 contd.

metamake.sh
Just need to redirect the error to null in case intel is not present.
=> redirect error when intel not present #262

CMakeLists.txt, src/DCDOutput.cpp, src/DCDlib.cpp, src/EnsemblePreprocessor.h, src/MolSetup.cpp, src/MolSetup.h, src/XYZArray.h, test/CMakeLists.txt.in, test/FileList.cmake, test/GoogleTest.cmake, test/src/BasicTypesTest.cpp, test/src/BitLibTest.cpp
This pull request adds Google Test to our code. To run Google test, you can simply run `bin/GOMC_Test`.
To add new tests, create a new file under `test/src/` and add that file to `test/FileList.cmake`.
=> Added googletest

src/DCDOutput.cpp
Otherwise, it will overwrite some of the memory.
=> Need to allocate one more character for null character

lib/Random123/features/nvccfeatures.h, lib/Random123/features/sse.h, src/GPU/CalculateEnergyCUDAKernel.cu, src/GPU/CalculateForceCUDAKernel.cu
Made few changes to the Random123 library to make it work for Visual Studio 2019 and CUDA 11.1.
=> Fixes compilation of GPU on windows

src/CalculateEnergy.cpp, src/Ewald.cpp, src/StaticVals.cpp, src/StaticVals.h, src/System.cpp, src/System.h
Now only System object would take care of BoxDimensions initialization.
=> Fix to the BoxDimensions initialization from XSC files

src/CellList.cpp, src/GPU/TransformParticlesCUDAKernel.cu, src/GPU/TransformParticlesCUDAKernel.cuh, src/System.cpp, src/moves/MultiParticle.h, src/moves/MultiParticleBrownianMotion.h
Perform error checking in Brownian kernel to make sure trial displacement would not put any molecule outside of the simulation box. Fix the bug in calculating reciprocal energy.  Use 32 thread/block to improve performance of large system.
=> Fix issues with MultiParticle Brownian.

src/ConsoleOutput.cpp, src/ConsoleOutput.h
=> Z and H in log file

lib/AlphaNum.h, src/DCDlib.cpp
Resolve errors and warnings when building on Windows with MS Visual Studio.
=> Fix #383: Resolve Warnings and Errors for Windows builds

src/GPU/CalculateForceCUDAKernel.cu
This is a tested version of the optimized BoxForceGPU function that we worked on during the most recent hackathon.
This code was tested for two different systems. For the one without electrostatics, the MP move (not just the BoxForce function) was sped up 38%. With electrostatics, the MP move was sped up 11%. Both runs produced matching results.
These systems are different, so the results can't be directly compared, but it's clear that the optimized function is faster.
=> Update to BoxForceGPU function that was optimized during the hackathon

src/ConsoleOutput.cpp
These are now left justified to resolve issue #483.
=> Fix formatting of titles like ETITLE

src/BoxDimensions.cpp, src/ConfigSetup.cpp, src/Ewald.cpp, src/FFSetup.cpp, src/GPU/CalculateForceCUDAKernel.cu, src/GPU/CalculateMinImageCUDAKernel.cuh, src/MoveSettings.cpp, src/PRNG.h, src/Simulation.cpp
=> Use standard library abs

src/Main.cpp
=> Fix memory leak in PrintHardwareInfo()
